services:
  api:
    build:
      context: .
    env_file:
      - .env
    environment:
      PORT: ${PORT:-8085}
    restart: unless-stopped
    network_mode: host

  migrate:
    build:
      context: .
    env_file:
      - .env
    environment:
      PORT: ${PORT:-8085}
    entrypoint: ["/app/migrate"]
    restart: "no"
    network_mode: host
